### ISSUE TITLE
interpolation error

### ISSUE THREAD

**Issue by nag92** [WPI-AIM/AIM_Vicon#4]
I am getting some errors when trying to interpolate. Its not on every file: "subject_05/subject_05_stair_config1_01.csv" file failed. 

I am getting the following error:

```
Traceback (most recent call last):
  File "/home/nathanielgoldfarb/stair_traj_learning/Training/Joint.py", line 83, in <module>
    hills = get_index(file_list)
  File "/home/nathanielgoldfarb/stair_traj_learning/Training/Joint.py", line 46, in get_index
    trial = ViconGaitingTrial.ViconGaitingTrial(vicon_file=file)
  File "/home/nathanielgoldfarb/stair_traj_learning/lib/GaitAnalysisToolkit/Session/ViconGaitingTrial.py", line 68, in __init__
    self._vicon = Vicon.Vicon(vicon_file)
  File "/home/nathanielgoldfarb/stair_traj_learning/lib/GaitAnalysisToolkit/lib/Vicon/Vicon.py", line 89, in __init__
    self.data_dict = self.open_vicon_file(self._file_path, verbose=verbose, interpolate=interpolate)
  File "/home/nathanielgoldfarb/stair_traj_learning/lib/GaitAnalysisToolkit/lib/Vicon/Vicon.py", line 415, in open_vicon_file
    category=output, interpolate=interpolate)
  File "/home/nathanielgoldfarb/stair_traj_learning/lib/GaitAnalysisToolkit/lib/Vicon/Vicon.py", line 557, in _extract_values
    s = s.interpolate(method='akima', limit_direction='both')
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 6835, in interpolate
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals/managers.py", line 519, in interpolate
    return self.apply('interpolate', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals/managers.py", line 395, in apply
    applied = getattr(b, f)(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals/blocks.py", line 1146, in interpolate
    downcast=downcast, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals/blocks.py", line 1212, in _interpolate
    interp_values = np.apply_along_axis(func, axis, data)
  File "/home/nathanielgoldfarb/.local/lib/python2.7/site-packages/numpy/lib/shape_base.py", line 380, in apply_along_axis
    res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals/blocks.py", line 1209, in func
    bounds_error=False, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/missing.py", line 239, in interpolate_1d
    order=order, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/missing.py", line 311, in _interpolate_scipy_wrapper
    new_y = method(x, y, new_x, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/missing.py", line 407, in _akima_interpolate
    P = interpolate.Akima1DInterpolator(xi, yi, axis=axis)
  File "/home/nathanielgoldfarb/.local/lib/python2.7/site-packages/scipy/interpolate/_cubic.py", line 288, in __init__
    raise ValueError("at least 2 breakpoints are needed")
ValueError: at least 2 breakpoints are needed

Process finished with exit code 1

```

**Comment by ajlewis02** [comment]
Looks like this error happens because the category in question (and quite a few others, in that specific spreadsheet) consists of one data entry and a long list of NaNs. More generally, it seems like the akima interpolator fails when it doesn't have enough data to actually form an Akima spline.

The best way I can see to handle this case is just to use linear interpolation for the whole dataset in question.
